trailersplus/api/urls.py
from django.urls import path
from rest_framework import routers

from . import views

router = routers.SimpleRouter()
router.register(r"locations", views.LocationViewSet, basename="locations")

urlpatterns = router.urls
urlpatterns += [
    path(
        "forms/lower_price", views.LowerPriceCreate.as_view(), name="Lower Price Form"
    ),
    path(
        "forms/appointment", views.AppointmentCreate.as_view(), name="Appointment Form"
    ),
    path("forms/custom", views.CustomCreate.as_view(), name="Custom Trailer Form"),
    path("forms/fleet", views.FleetCreate.as_view(), name="Fleet Trailers Form"),
    path("trustpilot/", views.review_create, name="TrustPilot Webhook"),
    path("product_reviews/", views.ProductReviewsList.as_view(), name='Product Reviews'),
    path("count_trailers/", views.TrailersCount.as_view(), name='Trailers Count'),
    path("session_cart/", views.CartSession.as_view(), name="Session Cart"),
    path("user_location/", views.UserLocation.as_view(), name="Session User Location"),
    path("checkout/", views.CheckoutView.as_view(), name="Checkout view")
]

trailersplus/product/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ProductPage

urlpatterns = [
    path(
        "<str:state>/<str:city>/inventory/",
        TemplateView.as_view(template_name="utils/product-list.html"),
    ),
    path("<str:state>/<str:city>/<str:vin>/", ProductPage.as_view()),
]

trailersplus/product/models/django.py
from django.db import models
from django.contrib.postgres.fields import ArrayField, JSONField
from django.core.exceptions import ObjectDoesNotExist

ENGLISH = "EN"
SPANISH = "ES"
LANGUAGE_CHOICES = [
    (ENGLISH, "English"),
    (SPANISH, "Spanish"),
]


def DEFAULT_WORK_HOURS():
    return {
        "sunday_hours": None,
        "monday_hours": None,
        "tuesday_hours": None,
        "wednesday_hours": None,
        "thursday_hours": None,
        "friday_hours": None,
        "saturday_hours": None,
    }


class SecondDbManager(models.Manager):
    def get_queryset(self):
        qs = super().get_queryset()

        # if `use_db` is set on model use that for choosing the DB
        if hasattr(self.model, "use_db"):
            qs = qs.using(self.model.use_db)

        return qs


class SecondDbBase(models.Model):
    use_db = "default"
    objects = SecondDbManager()

    class Meta:
        abstract = True


class Trailer(SecondDbBase):
    vin = models.CharField("VIN number", max_length=21, primary_key=True)
    store = models.ForeignKey(
        "Location",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name="Trailer's location",
    )
    category = models.ForeignKey(
        "Category", on_delete=models.PROTECT, verbose_name="Trailer's type", null=True
    )
    # primary_web_category = models.CharField('Web Category', max_length=255)
    # ToDo Signal to set up
    order_number = models.IntegerField(null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)
    sale_price = models.DecimalField(
        max_digits=12, decimal_places=2, null=True, blank=True
    )
    cash_price = models.CharField(max_length=45, null=True, blank=True)
    calculated_cash_price = models.CharField(max_length=45, null=True, blank=True)
    msrp = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)

    width = models.CharField(max_length=5, null=True, blank=True)
    length = models.CharField(max_length=5, null=True, blank=True)
    gvwr = models.IntegerField(null=True, blank=True)
    gawr = models.IntegerField(null=True, blank=True)
    empty_weight = models.IntegerField(null=True, blank=True)
    overall_height = models.IntegerField(null=True, blank=True)
    overall_length = models.IntegerField(null=True, blank=True)
    overall_width = models.IntegerField(null=True, blank=True)
    interior_height = models.IntegerField(null=True, blank=True)
    interior_length = models.IntegerField(null=True, blank=True)
    interior_width = models.IntegerField(null=True, blank=True)
    rear_door_height = models.IntegerField(null=True, blank=True)
    rear_door_width = models.IntegerField(null=True, blank=True)
    platform_height = models.IntegerField(null=True, blank=True)
    hitch_height = models.IntegerField(null=True, blank=True)
    frame_centers = models.IntegerField(null=True, blank=True)
    roof_centers = models.IntegerField(null=True, blank=True)
    wall_centers = models.IntegerField(null=True, blank=True)
    axles = models.IntegerField(null=True, blank=True)
    stone_guard = models.IntegerField(null=True, blank=True)
    door_type = models.CharField(max_length=50, null=True, blank=True)
    coupler = models.CharField(max_length=25, null=True, blank=True)
    coupler_size = models.CharField(max_length=255, null=True, blank=True)

    sale_date = models.DateField(null=True, blank=True)
    delivery_date = models.DateField(null=True, blank=True)
    year = models.CharField(max_length=45, null=True, blank=True)
    model = models.CharField(max_length=45, null=True, blank=True)

    pictures = ArrayField(JSONField(), verbose_name="Pictures list", null=True)

    def __str__(self):
        return self.vin

    class Meta:
        ordering = ['sale_price']


class TrailerTranslation(SecondDbBase):
    trailer = models.ForeignKey(
        Trailer, on_delete=models.CASCADE, verbose_name="Related trailer"
    )
    language = models.CharField(max_length=2, choices=LANGUAGE_CHOICES, default=ENGLISH)

    actual_color = models.CharField(max_length=50, null=True, blank=True)
    color = models.CharField(max_length=50, null=True, blank=True)
    axle_warranty = models.CharField(max_length=255, null=True, blank=True)
    roof_warranty = models.CharField(max_length=255, null=True, blank=True)
    warranty = models.CharField(max_length=255, null=True, blank=True)
    tires = models.CharField(max_length=255, null=True, blank=True)
    wheels = models.CharField(max_length=255, null=True, blank=True)
    doors = models.CharField(max_length=75, null=True, blank=True)
    stabilizer_jacks = models.CharField(max_length=255, null=True, blank=True)
    side_door = models.CharField(max_length=255, null=True, blank=True)
    rear_door = models.CharField(max_length=255, null=True, blank=True)
    side_walls = models.CharField(max_length=255, null=True, blank=True)
    suspension = models.CharField(max_length=255, null=True, blank=True)
    frame = models.CharField(max_length=255, null=True, blank=True)
    brakes = models.CharField(max_length=255, null=True, blank=True)
    floor = models.CharField(max_length=255, null=True, blank=True)
    clearance_lights = models.CharField(max_length=255, null=True, blank=True)
    tail_lights = models.CharField(max_length=255, null=True, blank=True)
    protected_undercarriage = models.CharField(max_length=255, null=True, blank=True)

    long_description = models.TextField(blank=True, null=True)
    short_description = models.CharField(max_length=50, blank=True, null=True)
    package = models.CharField(max_length=255, null=True, blank=True)
    tag = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return f"{self.language} {self.trailer.vin}"

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["language", "trailer_id"], name="unique_translation"
            )
        ]
        verbose_name = "Trailer's translation"
        verbose_name_plural = "Trailers' translations"


class Location(SecondDbBase):
    STATE_CHOICES = [
        ("AL", "Alabama"),
        ("AK", "Alaska"),
        ("AZ", "Arizona"),
        ("AR", "Arkansas"),
        ("CA", "California"),
        ("CO", "Colorado"),
        ("CT", "Connecticut"),
        ("DE", "Delaware"),
        ("FL", "Florida"),
        ("GA", "Georgia"),
        ("HI", "Hawaii"),
        ("ID", "Idaho"),
        ("IL", "Illinois"),
        ("IN", "Indiana"),
        ("IA", "Iowa"),
        ("KS", "Kansas"),
        ("KY", "Kentucky"),
        ("LA", "Louisiana"),
        ("ME", "Maine"),
        ("MD", "Maryland"),
        ("MA", "Massachusetts"),
        ("MI", "Michigan"),
        ("MN", "Minnesota"),
        ("MS", "Mississippi"),
        ("MO", "Missouri"),
        ("MT", "Montana"),
        ("NE", "Nebraska"),
        ("NV", "Nevada"),
        ("NH", "New Hampshire"),
        ("NJ", "New Jersey"),
        ("NM", "New Mexico"),
        ("NY", "New York"),
        ("NC", "North Carolina"),
        ("ND", "North Dakota"),
        ("OH", "Ohio"),
        ("OK", "Oklahoma"),
        ("OR", "Oregon"),
        ("PA", "Pennsylvania"),
        ("RI", "Rhode Island"),
        ("SC", "South Carolina"),
        ("SD", "South Dakota"),
        ("TN", "Tennessee"),
        ("TX", "Texas"),
        ("UT", "Utah"),
        ("VT", "Vermont"),
        ("VA", "Virginia"),
        ("WA", "Washington"),
        ("WV", "West Virginia"),
        ("WI", "Wisconsin"),
        ("WY", "Wyoming"),
        ("DC", "District of Columbia"),
        ("MH", "Marshall Islands"),
    ]
    store_id = models.CharField(max_length=100, primary_key=True)
    state = models.CharField(max_length=2, choices=STATE_CHOICES)
    active = models.BooleanField(default=True)
    store_name = models.CharField(max_length=100, null=True, blank=True)
    store_city = models.CharField(max_length=100, null=True, blank=True)
    store_address = models.CharField(max_length=500, null=True, blank=True)
    store_zip = models.IntegerField(null=True, blank=True)
    store_directions = models.TextField(null=True, blank=True)
    store_spanish_directions = models.TextField(null=True, blank=True)
    store_email = models.EmailField(max_length=255, null=True, blank=True)
    store_map_url = models.URLField(max_length=500, null=True, blank=True)
    store_phone = models.CharField(max_length=45, null=True, blank=True)
    store_keywords = ArrayField(models.CharField(max_length=45))
    store_lat = models.CharField(max_length=45, null=True, blank=True)
    store_long = models.CharField(max_length=45, null=True, blank=True)
    store_description = models.CharField(max_length=255, null=True, blank=True)
    store_title = models.CharField(max_length=255, null=True, blank=True)
    work_hours = JSONField(default=DEFAULT_WORK_HOURS)

    def get_city_name(self):
        return self.store_name.replace('TrailersPlus ', '')

    def get_slug(self):
        try:
            return self.pages.first().get_slug()
        except (ObjectDoesNotExist, AttributeError):
            return ''

    def __str__(self):
        return f'{self.get_city_name()}({self.store_city}), {self.state}'


class CategoryFilter(models.Model):
    FILTER_CHOICES = [
        ("exact", "Exact"),
        ("contains", "Contains"),
        ("startswith", "Starts With"),
        ("endswith", "Ends With"),
        ("regex", "Regex"),
    ]
    FIELDS_CHOICES = [
        ("category__web_category", "Web Category"),
        ("coupler", "Coupler"),
    ]
    case_sensitive = models.BooleanField('Case Sensitive?')
    type = models.CharField(max_length=15, choices=FILTER_CHOICES, help_text="SQL Regex https://dataschool.com/how-to-teach-people-sql/how-regex-works-in-sql/")
    field_name = models.CharField(max_length=25, choices=FIELDS_CHOICES, null=False, blank=False, default='category__web_category__')
    filter = models.CharField(max_length=25)

    def __str__(self):

trailersplus/streams/models.py
from django.db import models

# Create your models here.

trailersplus/my_store/views.py
from django.shortcuts import render

# Create your views here.

trailersplus/product/views.py
from django.views import View
from .models import Trailer, Location
from django.shortcuts import get_object_or_404, get_list_or_404, render


class ProductPage(View):
    from_type = None

    def get(self, request, state, city, vin):
        # store = get_object_or_404(Location, state=state, store_city=city)
        # trailer = get_object_or_404(Trailer, vin=vin, store=store)
        return render(request, "product-page.html")

trailersplus/streams/views.py
from django.shortcuts import render

# Create your views here.

trailersplus/my_store/templates/streams/my_store/banner.html
{% load wagtailcore_tags wagtailimages_tags %}
{% load static %}
<!-- Banner start -->
<section class="padding-50b padding-md-75t padding-md-80b tp-banner tp-banner--bot tp-banner--600 tp-banner--overl-5 bg-img {% if message is not None%}tp-banner--with-message"{% endif %}>
    <picture>
            {% image self.background_image width-1920 format-webp as image_webp %}
            <source data-srcset="{{ image_webp.url }}" type="image/webp" media="(min-width: 451px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            {% image self.background_image_mobile width-450 format-webp as image_webp %}
            <source data-srcset="{{ image_webp.url }}" type="image/webp" media="(max-width: 450px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            {% image self.background_image width-1920 format-jpeg as image_jpeg %}
            <source data-srcset="{{ image_jpeg.url }}" type="image/jpeg" media="(min-width: 451px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            {% image self.background_image_mobile width-450 format-jpeg as image_jpeg %}
            <source data-srcset="{{ image_jpeg.url }}" type="image/jpeg" media="(max-width: 450px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            {% image self.background_image width-1920 as image_webp %}
            <img data-src="{{ image_webp.url }}" alt="alt" class="lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
    </picture>
    {% if message is not None%}
        <!-- Warning Message BEGIN -->
        <div class="margin-40b margin-md-20b">
            <div class="tp-warning-message container">
                <div class="tp-warning-message__wrapper">
                    <p>{{ message.text }}</p>
                </div>
            </div>
        </div>
        <!-- Warning Message END -->
    {% endif %}
    <div class="container c-white t-left">
        <h1 class="h1 c-white margin-10t margin-0b br-lg ">{{ store.store_name }}</h1>
        <p class="c-white margin-20t br-sm">{{ self.description }}</p>
    </div>
</section>
<!-- Banner end -->

trailersplus/my_store/templates/streams/my_store/call_today.html
{% load wagtailcore_tags wagtailimages_tags %}
{% load static %}
<!-- Call Today start -->
<section class="tp-cut-red c-white p-relative">
    <div class="bg-sect bg-img">
        <picture>
            {% image self.background_image width-1920 format-webp as image_webp %}
            <source data-srcset="{{ image_webp.url }}" type="image/webp" media="(min-width: 451px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            {% image self.background_image_mobile width-450 format-webp as image_webp %}
            <source data-srcset="{{ image_webp.url }}" type="image/webp" media="(max-width: 450px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            {% image self.background_image width-1920 format-jpeg as image_jpeg %}
            <source data-srcset="{{ image_jpeg.url }}" type="image/jpeg" media="(min-width: 451px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            {% image self.background_image_mobile width-450 format-jpeg as image_jpeg %}
            <source data-srcset="{{ image_jpeg.url }}" type="image/jpeg" media="(max-width: 450px)" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            {% image self.background_image width-1920 as image_webp %}
            <img data-src="{{ image_webp.url }}" alt="alt" class="lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
        </picture>
    </div>
    <div class="container p-relative">
        <div class="tp-cut-red__img">
            <picture>
                {% image self.somewhy_happy_guy_image width-166 format-webp as image_webp %}
                <source data-srcset="{{ image_webp.url }}" type="image/webp" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
                {% image self.somewhy_happy_guy_image width-166 format-jpeg as image_jpeg %}
                <source data-srcset="{{ image_jpeg.url }}" type="image/jpeg" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
                {% image self.somewhy_happy_guy_image width-166 format-jpeg as image_jpeg %}
                <img data-src="{{ image_jpeg.url }}" alt="Call today" class="lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
            </picture>
        </div>
        <div class="row">
            <div class="col-12 col-md-9 col-lg-6 col-xl-4 offset-xl-2 margin-30b margin-lg-0b">
                <div class="__text">
                    <h2 class="h4 c-white">{{ self.title}}</h2>
                    <h3 class="h3 c-white">{{ self.call_today }} <a class="fw700 c-white" href="tel:+1{{ store.store_phone }}">{{ store.store_phone }}</a></h3>
                </div>
            </div>
            <div class="col-12 col-md-9 col-lg-6 col-xl-5 offset-xl-1">
                <ul class="tp-check-list tp-check-list--white-txt tp-check-list--small">
                    {% for point in self.points %}
                    <li>{{ point }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- Call Today end -->

trailersplus/my_store/templates/streams/my_store/customer_reviews.html
{% load wagtailcore_tags wagtailimages_tags %}
{% load static %}
<!-- Customer Reviews start -->
<section class="tp-section--default bg-grey">
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <div class="tp-review-slider">
                    <div class="tp-review-slider__bg bg-img">
                        <picture>
                            {% image self.background_image format-webp as image_webp %}
                            <source data-srcset="{{image_webp.url}}" type="image/webp" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
                            {% image self.background_image format-jpeg as image_jpeg %}
                            <source data-srcset="{{image_jpeg.url}}" type="image/jpeg" srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
                            {% image self.background_image format-jpeg as image_jpeg %}
                            <img data-src="{{ image_jpeg.url }}" alt="Call today" class="lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
                        </picture>
                    </div>
                    <h3 class="c-white h3 margin-0t p-relative z-index">{{ self.reviews_title }}</h3>
                    <div class="tp-review-slider__content">
                        <div class="tp-swiper tp-swiper--review-2 js-swiper">
                            <div class="tp-swiper__container swiper-container" data-slides="1" data-simulate_touch="true" data-loop="true" data-speed="1000" data-autoplay="4000">
                                <div class="swiper-wrapper tp-swiper__wrapper">
                                    {% for review in self.reviews %}
                                    <div class="swiper-slide tp-swiper__slide">
                                        <div class="tp-review tp-review--white">
                                            <p class="tp-review__text">
                                                {{ review.review_text }}
                                            </p>
                                            <span class="tp-review__author d-block">{{ review.review_author}}</span>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="swiper-pagination tp-swiper__pagination margin-40t"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 offset-lg-1 d-flex align-items-center margin-25t margin-md-60t margin-lg-0t">
                <div>
                    <h3 class="h3 margin-15b margin-md-20b">{{ self.about_title }}</h3>
                    <p class="p-md">
                        {{ self.about_text }}
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Customer Reviews end -->

trailersplus/my_store/templates/streams/my_store/directions.html
{% load wagtailcore_tags wagtailimages_tags %}
{% load static %}
{% load product_tags %}
<!-- Direction start -->
<section class="bg-grey">
    <div class="container p-relative padding-50t padding-50b padding-md-85t padding-md-85b">
        <div class="tp-location__buttons">
            <a href="inventory/" class="tp-btn tp-btn--md tp-btn--red tp-btn--view">
                <span>{{ self.view_inventory }}</span>
            </a>
            <a href="#direction-popup" class="tp-btn tp-btn--md tp-btn--red tp-btn--direction js-popup">
                <span>{{ self.get_directions}}</span>
            </a>
        </div>
        <div class="row margin-md-25t">
            <div class="col-lg-7">
                <div class="tp-location__info">
                    <div class="tp-location__info-col">
                        <h2 class="tp-location__name">
                            {{ store.store_name }}
                        </h2>
                        <address class="tp-location__address">
                            {{ store.store_address }}
                            <br>
                            {{ store.store_city }}, {{ store.state }} {{ store.store_zip }} <br>
                            Phone:
                            <a href="tel:+1{{ store.store_phone }}">{{ store.store_phone }}</a>
                        </address>
                    </div>
                    <div class="tp-location__info-col">
                        <div class="tp-location__schedule margin-md-5t">
                            <h3 class="h4">{{ self.store_hours }}</h3>
                            <!-- TODO "CLOSED" must be uppercase -->
                            <table>
                                <tbody>
                                    {{ store.work_hours|group_work_hours }}
                                </tbody>
                            </table>
                            <p class="margin-20t">
                                <a href="#appointment-only" class="js-popup">{{ self.learn_why_appointment }}</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-5">
                <div class="tp-location__map">
                    <div class="tp-map js-simple-map" data-lat="{{ store.store_lat }}" data-lng="{{ store.store_long }}" data-zoom="15" data-fullscreen_control="true" data-scrollwheel="true" data-marker="{% static 'img/logo-img50.svg' %}"></div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Direction end -->

trailersplus/my_store/templates/streams/my_store/directions_popup.html
{% load static product_tags%}
<!-- Get Direction Popup start -->
<div id="direction-popup" class="white-popup mfp-hide tp-popup">
    <div class="tp-popup__body">
        <div class="tp-direct-popup">
            <div class="tp-direct-popup__logo">
                <img src="{% static 'img/logo-img50.svg' %}" alt="City Name">
                {{ store.store_name }}
            </div>
            <div class="row margin-30t">
                <div class="col-md-6">
                    <div>
                        <img src="{% static 'img/icons/google-maps.png' %}" alt="Google maps">
                    </div>
                    <a href="{{ store.store_map_url }}" class="tp-btn tp-btn--red tp-btn--md margin-10t" target="_blank" rel="noopener">{{ self.go_to_google_maps }}</a>
                </div>
                <div class="col-md-6">
                    <div class="margin-20t">
                        <div class="tp-loc-info-item">
                            <i class="fa fa-map-marker"></i>
                            <div>
                                {{ store.store_name }} <br> {{ store.store_address }}
                                {{ store.get_state_display }} {{ store.store_zip }}
                            </div>
                        </div>
                        <div class="tp-loc-info-item">
                            <i class="fa fa-phone"></i>
                            <div>
                                <a href="tel:+1{{ store.store_phone }}">{{ store.store_phone }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tp-direct-popup__info margin-25t margin-md-35t">
                <span class="h4 c-main">{{ self.directions }}</span>
                {% if locale == 'es' %}
                    <p>
                        {{ store.store_spanish_directions|safe }}
                    </p>
                {% else %}
                    <p>
                        {{ store.store_directions|safe }}
                    </p>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<!-- Get Direction Popup end -->

trailersplus/my_store/templates/streams/my_store/long_text.html
{% load wagtailcore_tags wagtailimages_tags %}
{% load static product_tags common_tags%}
<!-- Text info start -->
<section class="tp-section">
    <div class="container tp-text">
        {{ store.get_city_name|one_more:store.get_state_display|add_store:self.text|add_phone:store.store_phone|safe }}
        {% if locale == 'es' %}
            <p>
            {{ store.store_spanish_directions|safe }}
            </p>
        {% else %}
            <p>
            {{ store.store_directions|safe }}
            </p>
        {% endif %}
    </div>
</section>
<!-- Text info end -->

trailersplus/my_store/templates/streams/my_store/one_stop.html
{% load wagtailcore_tags wagtailimages_tags %}
{% load static %}
<!-- One-Stop start -->
<section class="padding-45t padding-20b padding-md-75t padding-md-15b">
    <div class="container">
        <h2 class="h2 t-center margin-30b margin-md-70b">{{ self.title }}</h2>
        <div class="row">
            {% for bullet in self.bullets %}
            <div class="col-md-6 margin-25b margin-md-65b">
                <div class="tp-store-serv">
                    <div class="tp-store-serv__title">
                        {% image bullet.icon format-jpeg as icon%}
                        <img data-src="{{ icon.url }}" alt="{{ bullet.icon_alt }}" class="lazyload" src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==">
                        <h3 class="h4 margin-0t">{{ bullet.title }}</h3>
                    </div>
                    <p class="p-md">{{ bullet.text }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
<!-- One-Stop end -->